name: Codecov

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test:
    name: Upload coverage
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          file: lcov.info
